### ISSUE TITLE
"DEC_rename" etc in the parameter list?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/frontend-tab-generator#20]
![image](https://github.com/oda-hub/frontend-tab-generator/assets/3909535/b1460d92-97b9-4151-a626-32ff93b29d33)

built from https://gitlab.renkulab.io/astronomy/mmoda/ibis-isgri-spectrum/-/blob/main/isgri-full-image-sextractor.ipynb?ref_type=heads

**Comment by dsavchenko** [comment]
Probably it's not documented, but this is intentional. If the parameter have the name of the "source query" parameters (the ones from the top panel) but is not explicitly annotated, it gets renamed and is treated as an instrument parameter

**Comment by volodymyrss** [comment]
Ok, makes sense, but they are annotated, see repo link. Maybe not the right term?

**Comment by dsavchenko** [comment]
You are right, by explicitly I meant with special terms for these inputs: `oda:PointOfInterestRA`, `oda:PointOfInterestDec`
These terms are listed [here](https://odahub.io/docs/guide-development/#default-parameters)

Note that these parameters should be consistently annotated in all notebooks in the repo. Otherwise, the behaviour is not well-defined.
