### ISSUE TITLE
How can I display an output string ?

### ISSUE THREAD

**Issue by ferrigno** [oda-hub/frontend-tab-generator#51]
In my "expert" notebooks, I define
`uploaded_images_prod = TextLikeProduct(uploaded_images, name='Uploaded images')`
where `uploaded_images` is a string

Then I put in the output cell
`uploaded_images_url = uploaded_images_prod #oda:ODATextProduct`

but this creates an archive which needs to be downloaded and decompressed, while ideally, I would just like to show the input string.

**Comment by volodymyrss** [comment]
Did you have a look in [this example repository](https://renkulab.io/projects/astronomy/mmoda/mmoda-nb2workflow-example/files/blob/notebooks/text_picture_binfile.ipynb) referenced in [the doc](https://odahub.io/docs/guide-development/) ?

**Comment by ferrigno** [comment]
Exactly what I meants
https://gitlab.renkulab.io/astronomy/mmoda/jemx-expert/-/blob/main/mosaic.ipynb
(`uploaded_images_url = uploaded_images #oda:ODATextProduct ; oda:label "URL of images uploaded to gallery"`)
![Screenshot from 2024-09-05 10-32-45](https://github.com/user-attachments/assets/e3ff1d6e-ce37-4684-92a0-e59035e1ecf5)

I had to download a file, unzip it and open to see a string (empty in this case) Not the most convenient way to display an ASCII output: a window like for the token would be much better.

**Comment by dsavchenko** [comment]
It's empty, therefore you don't see it. Normally, the text is shown under "download" button.

**Comment by ferrigno** [comment]
Then, we can close it.  However, for the elegance of the tab, it would be better to have a window as done for the token with posdibility to copy in yhe clipboard, rather than this generic mechanism.

**Comment by volodymyrss** [comment]
> Then, we can close it. However, for the elegance of the tab, it would be better to have a window as done for the token with posdibility to copy in yhe clipboard, rather than this generic mechanism.

I think @dsavchenko is saying that it already shows in the window just like the token. It just shows nothing because your output is empty. Did you @ferrigno try to see what happens if there is an output?

By the way, as I said above, that's not about tab. Perhaps you @ferrigno are confusing modal window with product with an instrument tab - a totally different browser UI element, and also produced in a different place?

Anyway, if you @ferrigno have the remaining points, except for the possible misunderstanding you had, please comment and reopen the issue. But if there is nothing to add we can keep it closed.

**Comment by dsavchenko** [comment]
As a side note, the output as produced by the plugin is in most cases structured like the one for the image. I chose this way so that every product type is ingestible by the frontend without additional changes there. 
But this leads to misunderstandings, as we see. From showing products list as a table of "Images" to almost useless "download" button for simple text output etc.
We may want to adapt the frontend to better represent different products. Using it then will require rather small changes in the plugin.

**Comment by volodymyrss** [comment]
> Exactly what I meants https://gitlab.renkulab.io/astronomy/mmoda/jemx-expert/-/blob/main/mosaic.ipynb (`uploaded_images_url = uploaded_images #oda:ODATextProduct ; oda:label "URL of images uploaded to gallery"`) ![Screenshot from 2024-09-05 10-32-45](https://private-user-images.githubusercontent.com/2527219/364697838-e3ff1d6e-ce37-4684-92a0-e59035e1ecf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NzI4MTYsIm5iZiI6MTcyNTk3MjUxNiwicGF0aCI6Ii8yNTI3MjE5LzM2NDY5NzgzOC1lM2ZmMWQ2ZS1jZTM3LTQ2ODQtOTJhMC1lNTkwMzVlMWVjZjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTBUMTI0ODM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2NjZmEwNzk2YjhjY2EwYzE2YjRiMzE5NGU4ZGI2NmRkNTZkZDQzZDQzZWU2N2IzNjQ0ODQyNDJjMWM5ZjIwNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.J23Bvs9N5lWc_whEhXPBUtQCoH1pUa3KJZHBE4l0WQg)
> 
> I had to download a file, unzip it and open to see a string (empty in this case) Not the most convenient way to display an ASCII output: a window like for the token would be much better.

By the way, I just got an example of the text output, it's not what you wanted? This is how it was always working.

![image](https://github.com/user-attachments/assets/63a06f16-f802-47a4-8ed4-4104ce9b9580)
