### ISSUE TITLE
only one tab at the same time

### ISSUE THREAD

**Issue by dsavchenko** [oda-hub/frontend-tab-generator#7]

**Comment by dsavchenko** [comment]
@motame for this I really need your help with debugging

In the attached archive, there are three generated modules. If I install "altgw" first - the tab is shown up. Then, I install "legacy" - "altgw" tab disappears, "legacy" tab is shown up. 
Then "ant" - it replaces the tab, even if I disable and uninstall it – I am not able to get other instruments back (running drush dre doesn't help). Finally, I can only reenable tab for the last-used instrument: "ant". 

Probably, there are unnecessary steps here to reproduce the problem...

[testcase.zip](https://github.com/oda-hub/frontend-tab-generator/files/10437937/testcase.zip)

**Comment by dsavchenko** [comment]
or probably @burnout87 want to see on it
I really don't know how to properly debug drupal

**Comment by motame** [comment]
As explained in the issue https://github.com/oda-hub/mmoda-frontend-module/issues/187 the parameter roles_only should contain the list of roles (comma-separated) allowed to see the tab otherwise the tab will never show up :-)
Second issue is related to the setting parameter "weight", it tells mmoda how to sort the tabs.
The lowest is the weight the highest is it's priority : appears at the beginning !
The instruments are simply sorted in the tabs by ascending "weight".

You have now to comment/delete the parameter roles_only : 
    //'only_roles' => '',
Or set selected roles to see the instrument. Of course the roles should be created and assigned before hand :-) !
And set distinct weights for the three instruments. As the highest one for the time being is 100, you can use 110, 120, 130.

That what I just did and it works properly on my dev instance:
https://cdcidev.mtmco.net/mmoda

**Comment by motame** [comment]
By the way, concerning the weights a step of 10 is currently used to allow the possibility to insert instruments within existing tabs without changing other instruments.

**Comment by dsavchenko** [comment]
It's an obstacle for the generator, as it need to know weights of all other instruments. But at least I now understand the reason of this issue.
We may discuss on today's meeting.

**Comment by motame** [comment]
OK, let us discuss it in the meeting.
Showing the instruments in a random order is by far not user-friendly.
Users will be lost !

**Comment by motame** [comment]
Fixed and pushed to Github

**Comment by volodymyrss** [comment]
@dsavchenko please check and close

**Comment by motame** [comment]
Tested again and it's OK !
